settings:
  preview-block: LIME_STAINED_GLASS # The block that will be used to preview the mine's position
  max-display-name-length: 32 # The maximum length of the mine's display name
  only-create-on-own-plot: true # If false, they can also create PlotMines on plots they are members of

holograms:
  enabled: true # Whether to enable holograms (requires DecentHolograms plugin)
  update-interval: 2 # The interval in seconds that the hologram will update
  offset: 1.5 # The offset of the hologram (y-axis)
  text:
    - '<gold><b><name>' # Placeholders available: <name> (Display Name) | <mine> (Type) | <owner> (Owner) | <reset-percent> (Reset Percentage) | <mined-percent> (Mined Percentage) | <mined-blocks> (Mined Blocks) | <total-blocks> (Total Blocks)
    - '<gray>Owner: <owner>'
    - '<gray>Mined: <mined-percent>%'
    - '<gray>Reset: <reset-percent>%'
    - ''
    - '<gray>Click to manage'

mines:
  5x5_diamond_mine:
    width: 5 # The width of the mine
    depth: 5 # The depth of the mine
    reset-percent: 50.0 # The percentage of the mine that will be reset
    border: BEDROCK # The border surrounding the mine
    interaction-block: DIAMOND_BLOCK # The block that players will interact with to remove the mine
    creation_item: # The item that will be given to players to create the mine (/mine give <player> <mine>)
      material: MAGMA_CREAM
      custom-model-data: 0 # The custom model data of the item (optional)
      glow: true # Whether the item should glow
      display-name: "<aqua><b>5x5 Diamond Mine"
      lore:
        - "<gray>Mine with a 5x5 area"
        - "<gray>full of diamond ores"
        - ""
        - "<white>Place to create"
    composition: # The composition of the mine, add/remove as many as you want
      DIAMOND_ORE: 90 # The percentage of diamond ore in the mine
      STONE: 10